apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: 713859105457.dkr.ecr.us-east-1.amazonaws.com/bullboard-dashboard:latest
        ports:
        - containerPort: 4000

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: bullboard
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: bullboard
#   template:
#     metadata:
#       labels:
#         app: bullboard
#     spec:
#       containers:
#       - name: bullboard
#         image: 713859105457.dkr.ecr.us-east-1.amazonaws.com/bullboard-dashboard:latest
#         ports:
#         - containerPort: 6379
